-- AlterTable
ALTER TABLE `Travel` ADD COLUMN `Atmosphere` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `Clear` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `Clouds` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `Drizzle` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `Rain` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `Snow` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `Thunderstorm` BOOLEAN NOT NULL DEFAULT true;
